### ISSUE TITLE
Support integration an external Jenkins

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#161]
In many cases, users already have a Jenkins in their environment. But kubesphere always request us to install a new one. It will spend a lot of time to migrate the data file of Jenkins. The most important thing is that many people just don't know how to do it.

Support integration an external Jenkins could be an excellent feature. Please give me a thumb if you need this feature too.

**Comment by xiabai84** [comment]
That would be definitive a workaround for the current Kubesphere version with the problem that we don't have any template engine like "kustomize".

Als an Software Engineer I'd like to have a template engine, 
so that I can collect multiple microservice's deployments (or patches of them) into a big one and deploy the whole application  with only one jenkins job.

@LinuxSuRen  is that possible to integrate "kustomize" to the current jenkins deploy-container?

**Comment by LinuxSuRen** [comment]
> is that possible to integrate "kustomize" to the current jenkins deploy-container?

Sure. Please consider helping us to maintain the Jenkins agent images https://github.com/kubesphere/devops-agent

**Comment by xiabai84** [comment]
> > is that possible to integrate "kustomize" to the current jenkins deploy-container?
> 
> Sure. Please consider helping us to maintain the Jenkins agent images https://github.com/kubesphere/devops-agent

OK, I will try it.

**Comment by LinuxSuRen** [comment]
This issue just provides a solution to integrate the external Jenkins. But considering there are too many plugins that might cause unpredictable problems, we don't have a plan to support it as a product level.
/close
