### ISSUE TITLE
Sequence of PipelineRun is messy in some cases

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#360]
Please see the screenshot below:

<img src="https://user-images.githubusercontent.com/16865714/142557585-abcb7d22-ad8a-4152-8c2c-11fab276fe15.png" width=400>

![image](https://user-images.githubusercontent.com/16865714/142557865-2462d35c-5453-4afe-9175-dd80590cd7a1.png)

References:
- https://kubesphere.com.cn/forum/d/5994-kubesphere32devops (In Chinese)

I'm going to be in charge of this problem.

/kind bug
/priority high
/assign

**Comment by LinuxSuRen** [comment]
After doing some study, this problem might be caused by the `creationTimestamp` of the PipelineRun. Due 3.1 does not have the CRD PipelineRun, the problem might only come from the first time to create a lot of the old PipelineRuns.

So, I will give this issue new label until we have a solid conclusion.

/kind support
/remove-priority high
/priority medium
