### ISSUE TITLE
Suggest to add more information for continuous deployment parameters

### ISSUE THREAD

**Issue by chilianyi** [kubesphere/ks-devops#872]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

kubekey

### What happened?

<img width="1440" alt="截屏2022-12-15 16 06 38" src="https://user-images.githubusercontent.com/5917832/207806514-09d57659-b88f-4358-9b37-8870d74e4c6b.png">

Users can not understand the parameters when create continuous deployment, they should open the doc together:
https://kubesphere.io/zh/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment/#%E5%88%9B%E5%BB%BA%E6%8C%81%E7%BB%AD%E9%83%A8%E7%BD%B2

Suggest to add some info around the parameters, then users can use the create page only

**Comment by liyun95** [comment]
updated the parameter description in the documentation. check out: https://kubesphere.io/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment/

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:release-3.3`

![image](https://user-images.githubusercontent.com/68640256/215667409-b874d591-fc45-4f1b-bd87-29e06b4ca982.png)
![image](https://user-images.githubusercontent.com/68640256/215667451-3f9304e0-b29a-4b5c-b0de-f66ec58939f6.png)

![image](https://user-images.githubusercontent.com/68640256/215667258-9e85fbf1-fb5c-4792-ba03-c96bce0aae62.png)
![image](https://user-images.githubusercontent.com/68640256/215667287-aa78b9a5-2c89-4d18-8fba-fe02fc727c2d.png)
